{{- if .Values.secrets.create }}
{{- /* Database secret */ -}}
{{- if not .Values.database.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotrs.fullname" . }}-database
  labels:
    {{- include "gotrs.database.labels" . | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.database.type "mysql" }}
  mysql-root-password: {{ .Values.database.mysql.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
  mysql-user: {{ .Values.database.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.database.mysql.password | default (randAlphaNum 32) | b64enc | quote }}
{{- else }}
  postgres-user: {{ .Values.database.postgresql.user | b64enc | quote }}
  postgres-password: {{ .Values.database.postgresql.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
