{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goatflow.appSecretName" . }}
  labels:
    {{- include "goatflow.labels" . | nindent 4 }}
type: Opaque
data:
  app-secret-key: {{ .Values.secrets.appSecretKey | default (randAlphaNum 64) | b64enc | quote }}
{{- end }}
